### ISSUE TITLE
`Symbol.iterator` error on search sometimes

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#233]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Thursday Mar 15, 2018 at 12:09 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-app/issues/610 (0 comment(s))_

----

We keep getting scattered reports of this (I've seen both Android + iOS; none with web yet but it's random enough that it could still be a problem on web too)

Specifically: `Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined ` from Android and `TypeError: undefined is not an object (evaluating 'n.quests[Symbol.iterator]') ` on iOS.

Didn't work when they tried again in the same session, but did work when they restarted the app. So my first guesses would either be a memory / state management problem with the search results, or their auth gets messed up (maybe it expires? could see that happening especially if they leave it overnight or something and the OS doesn't kill it)

**Comment by smartin015** [comment]
Haven't seen this recur in Sentry - closing as obsolete.
