### ISSUE TITLE
Improve remote play reliability

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#235]
<a href="https://github.com/smartin015"><img src="https://avatars2.githubusercontent.com/u/607666?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smartin015](https://github.com/smartin015)**
_Sunday Mar 18, 2018 at 22:46 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-app/issues/616 (1 comment(s))_

----

- [ ] Server should recognize when both clients are on same event ID, but different quest line numbers
- [ ] >50% unit tests complete

**Comment by toddmedema** [comment]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toddmedema](https://github.com/toddmedema)**
_Monday Mar 19, 2018 at 04:07 GMT_

----

Some random notes I have lying around about JS testing techniques: (probably from the last time we did a testing sprint)

Reducer tests should test state changes via actions, specifically when there's logic involved / they aren't just glue

Use jasmine.objectContaining for more robust tests

Components: test branches for key content, i.e. if search results empty, make sure that resulting string contains "No results found"

Components: make sure that key interactivity works, i.e. that clicking the button calls the expected function
- see app/AdvancedPlay tests / enzyme / using spies

Containers: test when doing logic in mapping state or dispatch (i.e. not just glue) & test the logic
- i.e. the combat container
- see app/AdvancedPlayContainer, create a mock store, dispatch function, check that actions are dispatched with correct parameters.... this one goes too far and actually also tests the action


Actions: test actions with logic / not just glue
- ie Quest load node
- see app/actions/card - mock store, spy on outputs, expect the action with parameters to return an object containing
- if plain function, call directly. If dispatch-wrapped action, call store.dispatch(action)

**Comment by smartin015** [comment]
Unit testing and edge cases should happen as part of #234. Added the best practices to our README.
