### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#240]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Wednesday Apr 18, 2018 at 13:06 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-app/issues/653 (0 comment(s))_

----

As you play a quest, keep an autosave (perhaps debounced from the last action by 2s to prevent UI lag and exploding during remote play catchups)

Also show the most recent save at the top of featured quests

Also delete the autosave on the quest end event.

**Comment by smartin015** [comment]
Backlogging for now.
