### ISSUE TITLE
Address Multiplayer Sentry errors

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#245]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Monday May 07, 2018 at 00:49 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-app/issues/674 (0 comment(s))_

----

https://sentry.io/fabricate-llc/expedition-app/issues/540947529/?query=is:unresolved
https://sentry.io/fabricate-llc/expedition-app/issues/502698294/?query=is:unresolved
https://sentry.io/fabricate-llc/expedition-app/issues/543931488/?query=is:unresolved

**Comment by smartin015** [comment]
added to #234
