### ISSUE TITLE
Only allow multiplayer between apps running the latest version

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#248]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Thursday May 10, 2018 at 02:32 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-app/issues/679 (2 comment(s))_

----

In the same way we do the version check when fetching announcements, it might prevent headaches if we explicitly don't allow people to start / join multiplayer unless their app is running the latest version / show them a dialog indicating that they need to update their app to the latest version to play.

Perhaps simplest to disable the multiplayer menu button and show "please update" text in the button if outdated, rather than adding yet another dialog or leading on users any more than necessary

**Comment by toddmedema** [comment]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toddmedema](https://github.com/toddmedema)**
_Thursday Jun 21, 2018 at 00:32 GMT_

----

@ezittel this would be another good PR to learn on. We're currently fetching the "newest" app version and comparing it to the app's current version here - https://github.com/ExpeditionRPG/expedition/blob/master/services/app/app/actions/Announcement.tsx#L28

But we aren't storing it to the state. If we dispatched an action to update the announcement state to include something like `appUpToDate: boolean` (and add that field to the announcement store), we could then use that to change the multiplayer tool button to disable it and show "please update" text.

Let me know if that makes sense or if you have any questions!

**Comment by toddmedema** [comment]
<a href="https://github.com/ezittel"><img src="https://avatars0.githubusercontent.com/u/16277302?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ezittel](https://github.com/ezittel)**
_Thursday Jun 21, 2018 at 22:17 GMT_

----

Which button's text did you want to replace?  The 'join a session' button or 'online multiplayer' button on the card before that?

**Comment by smartin015** [comment]
Added as an edge case to #234
