### ISSUE TITLE
Find and fix single worst performance bottleneck

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#252]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Wednesday May 16, 2018 at 19:08 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-app/issues/687 (2 comment(s))_

----

One specific issue: pretty large lag after clicking buttons (one user specifically reported on iOS)

Ideas:
- try switching away from onTouchTap and to onClick, which modern mobile browsers supposedly support without a delay, but we'll want to test both on mobile web and mobile apps to confirm it still works as expected
  - (if we can't do that) is there a new way to do the touch intercept stuff? We might be subject to the 300ms input delay for some reason...
- streamline components to only need the store data they actually need - https://reactrocket.com/post/react-redux-optimization/
- onClick function takes 300ms on a 4x CPU throttle!
  - looks like render is getting called 5 times, each time takes 30ms. Relevant research: https://gist.github.com/paulirish/5d52fb081b3570c81e3a
- does disabling the CSS transition help? Might be a better way to do that in newer versions of React

Other more general performance optimizations, if it's still slow
- optimize CSS selectors
- disable hot module reloading and look at memory profile
  - disabling sound helps a lot - we could disable sound by default on all apps (not just the web version), but that would be sad :(

**Comment by toddmedema** [comment]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toddmedema](https://github.com/toddmedema)**
_Wednesday May 16, 2018 at 21:59 GMT_

----

Note that disabling sound largely resolved the issue, so perhaps we should default disable sound on all devices, and have the first time enable say that it will both use bandwidth and might slow down the app?

**Comment by toddmedema** [comment]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toddmedema](https://github.com/toddmedema)**
_Friday May 25, 2018 at 04:08 GMT_

----

Note - we might also just try switching away from onTouchTap and to onClick, which modern mobile browsers supposedly support without a delay, but we'll want to test both on mobile web and mobile apps

**Comment by smartin015** [comment]
can use the chrome performance tool for this.

**Comment by toddmedema** [comment]
https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108

**Comment by toddmedema** [comment]
https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108
