### ISSUE TITLE
Preserve # of rounds of combat in state

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#259]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Monday Jun 11, 2018 at 03:37 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-app/issues/735 (0 comment(s))_

----

And ideally # of combats - both for analytics, and so that we can persist knowledge about surge and skill check rotations across combat.

The really tricky thing here will be knowing when to clear this. For example, it should be easy in a quest - keep it as part of the quest state, and drop the quest state when you leave the quest. But the way we currently do GM mode (hopping backwards on victory and defeat) would require an unhealthy amount of duct tape to `RETURN`. Perhaps we instead adjust GM mode to behave more like quests, where it keeps moving forward in state? Perhaps injecting a single roleplaying card between each fight? (which could be handy once we have skill checks, so that the DM could choose either a combat or skill check next...)

**Comment by smartin015** [comment]
Backlogging for now.
