### ISSUE TITLE
Migrate to Symbol operators  in Sequelize

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#263]
<a href="https://github.com/smartin015"><img src="https://avatars2.githubusercontent.com/u/607666?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smartin015](https://github.com/smartin015)**
_Friday Jan 26, 2018 at 13:37 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-api/issues/65 (0 comment(s))_

----

Notice on load of the API binary:

```
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13
```

**Comment by smartin015** [comment]
Baglogging.
