### ISSUE TITLE
CRON email(s)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#313]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Tuesday Oct 03, 2017 at 22:33 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-quest-creator/issues/394 (1 comment(s))_

----

A couple of possibilities for ways we could keep authors engaged:

- [ ] published a quest privately in the past 12 months, but no (public + non-tombstoned) quests, why'd they stop?
- [ ] inactive quest creator accounts (ie lastLogin > 1 month ago and < 12 months ago) we miss you! perhaps share some exciting news, like the latest contest
- [ ] only publicly published quest in past 3 months, what can we do to make your publishing experience better?
- [x] authors who published part of a series > 1 month ago, how's the next part going?

Note that it might be wise for us to add an unsubscribe option to QC emails soon (separate from Mailchimp email list) before we get flagged for spam. We'll also want to be extra careful about keeping track of when these fire / not firing them multiple times to respect authors.

**Comment by toddmedema** [comment]
<a href="https://github.com/7thSentinel"><img src="https://avatars0.githubusercontent.com/u/31975344?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [7thSentinel](https://github.com/7thSentinel)**
_Friday Dec 08, 2017 at 03:26 GMT_

----

I like the survey idea.  

I've only gotten one response back so far after reaching out to authors who have quests not publicly published.  

He thanked me for the e-mail but said he was busy with other projects at the moment. 

Might try reaching out to him again after the New Year comes.

**Comment by smartin015** [comment]
Backlogging this bug as we're unlikely to get to it any time soon.
