### ISSUE TITLE
Request: Empty action goes to goto automatically

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#316]
<a href="https://github.com/ArcanaIreanol"><img src="https://avatars0.githubusercontent.com/u/32588637?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ArcanaIreanol](https://github.com/ArcanaIreanol)**
_Tuesday Oct 10, 2017 at 18:45 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-quest-creator/issues/412 (2 comment(s))_

----

Sometimes, I'd have loved to have in my quest a moment when there are 3 choices, that sets different stuff in variables but only goes to one place after that.

Problem: when, after a choice, there is content consisting of variables sets, it creates an empty screen, with a next button.
It would be awesome to automatically go to next in that case. cause it's bad for user experience though it allows programmer to create more complex stuff

example:

```
_Test_

lorem ipsum dolor et sit amet

* choice 1

    {{variable = variable + 1}}

    **goto foo**

* choice 2

    {{variable = variable - 1}}

    **goto foo**

* choice 3

    **goto foo**
``` 

in this example, if you hit choice 1, you'll have an empty screen with a next button (to go to #foo). and the variable would be set to ++. same if choice2 (variable--).
and in choice 3 you'd directly go to #foo, without an empty screen in between (because there would be no need to update variable)

**Comment by toddmedema** [comment]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toddmedema](https://github.com/toddmedema)**
_Tuesday Oct 10, 2017 at 21:18 GMT_

----

That seems pretty reasonable! @smartin015 can you think of any reasons not?

**Comment by toddmedema** [comment]
<a href="https://github.com/danielwiktorczyk"><img src="https://avatars2.githubusercontent.com/u/24488852?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [danielwiktorczyk](https://github.com/danielwiktorczyk)**
_Monday Apr 09, 2018 at 02:57 GMT_

----

I was thinking of this too when writing my quest, would really like to see this be added!

**Comment by smartin015** [comment]
There's some details/edge cases in implementing this logic that add significant bloat to the way we parse quest logic... as an already-functional alternative, if you're going to the same node you can just do the following:

```markdown
_Test_ 

lorem ipsum dolor et sit amet

{{text = "this is the text of the card"}}

* choice 1
 
  {{a = 5}}
  {{text}}
  
* choice 2 
 
  {{a = 6}}
  {{text}}

_Final_

{{a}} was chosen previously
```

@ArcanaIreanol WDYT?

**Comment by smartin015** [comment]
Closing this one out since we have a workaround and this thread is stale.
