### ISSUE TITLE
Expose quest stats to writers (aggregate score, plays, individual ratings + reviews)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#337]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Wednesday May 09, 2018 at 01:11 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-quest-creator/issues/484 (0 comment(s))_

----

See https://github.com/ExpeditionRPG/expedition/issues/249 for thoughts on displaying reviews

**Comment by toddmedema** [comment]
This'll need an API endpoint to fetch all of this information for a specified quest, and then a toolbar button + dialog to display it in the quest creator

**Comment by smartin015** [comment]
Backlogging this to focus on app display experience (#249)
