### ISSUE TITLE
Grammar checking

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#338]
<a href="https://github.com/smartin015"><img src="https://avatars2.githubusercontent.com/u/607666?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smartin015](https://github.com/smartin015)**
_Wednesday May 16, 2018 at 23:33 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-quest-creator/issues/487 (1 comment(s))_

----

We have spell checking... we should also have grammar checking!

**Comment by toddmedema** [comment]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toddmedema](https://github.com/toddmedema)**
_Thursday May 17, 2018 at 02:13 GMT_

----

Note that we would really want grammar /suggestions/ not just underlines. And to have suggestions, we'd first need interactions: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/488

This is actually a duplicate of a backlog issue: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/342

One option would be https://www.languagetool.org/, which includes spellchecking and (at least of research a year ago) had an offline option we could host ourselves 

Note that any spellcheck solution would need to support custom vocabulary since there are a lot of traditionally uncommon RPG words like undead that spellcheckers might not allow by default.

**Comment by smartin015** [comment]
Backlogging for now.
