### ISSUE TITLE
Award a few loot points for rating, a few more for leaving a review

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#344]
Also opportunity: daily quest loot reward? Loot reward for playing "NEW" quests? Double reward for playing "experimental" quests, ie in-app beta testing new cards?

**Comment by JTimNolan** [comment]
How many loot points for each action?

**Comment by toddmedema** [comment]
Let's do 5 for rating, + a bonus 10 points for reviewing.

Both numbers should be defined as CONSTANTS in `/shared` so that they're easy to update across both the app's help text + api server's calculations in the future

**Comment by toddmedema** [comment]
Example of how to increment loot count: https://github.com/ExpeditionRPG/expedition/pull/380/files#diff-3a7b8063f6b71eb984b4cc79ed5bdca2R20

**Comment by toddmedema** [comment]
Moving this to the backlog since a loot point economy would end up being pretty complex to do right
