### ISSUE TITLE
catch/prevent/remove fetch() calls in unit tests

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#346]
We're using `fetch()` in our unit tests, and it's actually making http requests... when messing with mockFetch and failing to restore it, I found the following:

```
React init deviceready event adds backbutton listener FAILED                                                                       
Error: No fallback response defined for GET to http://betaapi.expeditiongame.com/announcements   
```

This may also happen elsewhere, and we should probably prevent this from happening everywhere (bad juju for e.g. a unit test to rely on deployed beta API behavior).

**Comment by toddmedema** [comment]
Backlogging for now since it's not causing any problems or flaky tests yet, and we have a lot of more urgent things to fix
