### ISSUE TITLE
Feature Request: Add ability to manually trigger a combat countdown

### ISSUE THREAD

**Issue by JTimNolan** [ExpeditionRPG/expedition#350]
Currently there's a couple different ways to plug in to the existing combat system, but I think there would be some cool possibilities for both unique combat ideas and other types of time-sensitive skill checks if we allow story authors to trigger the timer themselves, with configurable options (duration, number or percent of players needed, icon shown). I think we can pass the information back to the author via a variable available in the card.

**Comment by toddmedema** [comment]
Nice thinking! We're actually working on something along these lines as part of the next expansion (timed "skill checks") - so I'm going to close this issue for now and we can revisit once skill checks are out to see if they do the job or we want to expand their functionality :)
