### ISSUE TITLE
Update for native experience on iPhone X

### ISSUE THREAD

**Issue by LordZardeck** [ExpeditionRPG/expedition#366]
The app is not optimized for a native experience on the iPhoneX, it's smaller on the screen, and has a bunch of white background: 

![img_1485](https://user-images.githubusercontent.com/1145989/42460679-1eb8440e-8364-11e8-945c-3bd9a04a282f.PNG)

**Comment by toddmedema** [comment]
Looks like it should be pretty straightforward, if you're willing to give it a try! https://blog.phonegap.com/displaying-a-phonegap-app-correctly-on-the-iphone-x-c4a85664c493

**Comment by LordZardeck** [comment]
@toddmedema I am actually trying to get that very thing working, but I'm not having much luck. Is there a way to get live reload working on the iOS simulator? It's annoying to have to re-build the iOS every change

**Comment by LordZardeck** [comment]
@toddmedema Okay, so I was able to get it working by manually copying the files from `src/images/splash` to `www/images/splash` What is supposed to copy those files over? Also, I'm now getting the follwing result, which may be due to the mis-matched dimensions. Am i supposed to just resize or crop the largest image into the correct dimensions, or will your team take the source image and properly fit it into the right dimensions?
![iphone x - 11 3 2018-07-09 13-38-44](https://user-images.githubusercontent.com/1145989/42469502-8e44eb38-837d-11e8-8359-b49d550f3bfe.png)

**Comment by toddmedema** [comment]
Hmm, you shouldn't need to copy the images over manually - did you run `./setup.sh`? (apologies if the dev experience is a bit rough, you're the first person to contribute to the cordova development side of things!)

I'm happy to generate a new image of the appropriate size if you send me the dimensions - to keep things moving on your end, you might try using a placeholder image of the correct dimensions just to make sure the rest of the code is working as expected :)

**Comment by LordZardeck** [comment]
@toddmedema Submitted a PR in #368, however, someone will need to update the images with the correct ones in the right dimensions:

Default@2x~iphone~anyany.png - 1334x1334
Default@2x~iphone~comany.png - 750x1334
Default@2x~iphone~comcom.png - 1334x750
Default@3x~iphone~anyany.png - 2208x2208
Default@3x~iphone~anycom.png - 2208x1242
Default@3x~iphone~comany.png - 1242x2208
Default@2x~ipad~anyany.png - 2732x2732
Default@2x~ipad~comany.png - 1278x2732
