### ISSUE TITLE
Header doesn't stay in place when scrolling

### ISSUE THREAD

**Issue by LordZardeck** [ExpeditionRPG/expedition#369]
See example:

![screencast 2018-07-09 17-55-08](https://user-images.githubusercontent.com/1145989/42480103-5ec2b06a-83a1-11e8-925e-876f7fc28ed3.gif)

**Comment by toddmedema** [comment]
Good call, that could definitely be better!

**Comment by LordZardeck** [comment]
@toddmedema I can tackle this task, though it's probably going to require some re-work on the html structure and css that currently exists. Can you clarify to me why there is a bunch of empty elements, and if they are critical?

![expedition rpg companion app 2018-07-10 09-58-30](https://user-images.githubusercontent.com/1145989/42518656-f7243d48-8427-11e8-9c18-88ce058de293.png)

**Comment by toddmedema** [comment]
Those are most likely inserted by Material UI - but if they're being inserted by our code, they aren't strictly necessary. React used to have this thing where if you wanted to return multiple JSX elements, you had to wrap them in a single element, but now that you can just return an array of elements in React 16, that's no longer necessary and can be torn out (note that it will likely affect CSS hierarchies)

**Comment by LordZardeck** [comment]
Got it. I'll watch out for that
