### ISSUE TITLE
Saving bug: breaks when save made during combat

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#378]

**Comment by toddmedema** [comment]
Closing, duplicate of https://github.com/ExpeditionRPG/expedition/issues/244

**Comment by smartin015** [comment]
This isn't really a duplicate, it's a different bug relating to quest saving.

**Comment by smartin015** [comment]
But actually it looks like all the other reported bugs on that issue are combat-related, so nevermind.
