### ISSUE TITLE
Ask the user if they had a good experience and/or to rate the app after 3 quests

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#383]
Would be useful to regularly survey our players' Net Promoter Score to see if we're making meaningful improvements (and also to see how NPS changes as people play the game more, ie if we survey after quest 1, 5, 10, 20, 30, 40, ...)

Thinking something like the app store after you finish your first quest, and BGG after (your second+ quest where you leave a 4 star+ review) OR (your third quest).

This should appear as a Dialog element with the primary button be something like "Rate" or "Happy to Help", and the secondary one being "Cancel" or "No Thanks"

This should be calculated via the user's quest history state, so that we don't have to worry about storing / updating / tracking another variable.

**Comment by smartin015** [comment]
Reducing scope on this a bit.
