### ISSUE TITLE
App: User Account page

### ISSUE THREAD

**Issue by JTimNolan** [ExpeditionRPG/expedition#384]
Currently I don't think there's a way to do any of the following in the app. I think all of this could be built into an "account" page:

- See what account you are logged in as
- Log out
- See how many loot points you have
- View recently played quests / view quest history + feedback and ratings submitted

**Comment by nimish-gupta** [comment]
@toddmedema I am planning of working on this issue. Can you tell me from, where this feature will be called?
I am thinking of adding an `Account` Label in the Menu.

**Comment by toddmedema** [comment]
Yep! `Account` in the dropdown menu in the top right is perfect

Note that we already added quest history as one of the main tabs, so we can skip that part for the account page

**Comment by nimish-gupta** [comment]
Logout should be in the menu or it should be on the Account Page?

**Comment by toddmedema** [comment]
On the account page, either at the bottom or next to the email of the signed in user; expect it to be used so infrequently that we don't want to crowd the menu with it

**Comment by toddmedema** [comment]
Was thinking it would be a list of their ratings and review text, in time order (most recent first), with a button that jumps to that quest's details page (the page that shows you the info about the quest + has the big "play" button)
