### ISSUE TITLE
Spellcheck recommendations

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#397]
Prerequisite to: https://github.com/ExpeditionRPG/expedition/issues/339

Essentially, when we show that something is a spelling error, it would be awesome to let them right click it and see a little menu of alternate (valid) spelling options. Selecting one of those should replace the text.

Imagining the interaction with the Ace editor would work along the lines of @JTimNolan 's PR - https://github.com/ExpeditionRPG/expedition/pull/343

We'll also need to extend the Spellcheck class with a function that takes in a word, and provides the 1-3 nearest spelling options - https://github.com/ExpeditionRPG/expedition/blob/master/services/quests/src/Spellcheck.tsx

If there's no word within, say, 10 letter modifications, we should show a disabled "No spelling recommendations" in the dropdown.

**Comment by smartin015** [comment]
Backlogging for now.
