### ISSUE TITLE
Quest Editor: Most recent quest

### ISSUE THREAD

**Issue by JTimNolan** [ExpeditionRPG/expedition#411]
I think it would be a much nicer UX if saved a cookie/localstorage item for the most recently edited document and opened that instead of creating a new document in the user's drive every time they click that get started button

**Comment by toddmedema** [comment]
Agreed. We'll likely be migrating off Google Docs in the next 6 months or so, since they're disabling the realtime API - at which point it'll be much easier to implement proper file management. But, welcome a quick fix to address this problem in the meantime!

**Comment by smartin015** [comment]
Added as an item to #535
