### ISSUE TITLE
Make enabling new content sets more apparent

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#455]
Perhaps if you don't have all the content sets, it shows you a (dismissable) banner at the top? (that's dismissed until the next content set comes out)

Could help drive sales... could also come off as spammy. Perhaps if it just linked to settings, and then improved the content prompt (perhaps even as simple as not showing the "can always change in settings" line if you're in settings, to make the "get a copy" link higher in the hierarchy)

What should the text be? "Enable (The Horror / The Future) expansion for even more content!"?

**Comment by smartin015** [comment]
I think this makes sense to have on the search filters page, when the app has settings indicating not all expansions are present and a filter is turned on for an expansion that isn't in settings.

**Comment by smartin015** [comment]
Actually having options for content sets on the settings page actually does this pretty well. They start disabled with a hit to go to settings, and when selecting a new expansion set there's a call to buy the cards. I think we can close this out.
