### ISSUE TITLE
card BG icons with underscores break QDL parsing

### ISSUE THREAD

**Issue by jamesabowling** [ExpeditionRPG/expedition#482]
Rune icons cannot currently be used as background icons using the {"icon":"xxxxx"} syntax because of the _ (underscore) character in their names which appear to break the title parsing.

**Comment by toddmedema** [comment]
Thanks for reporting this! Is this blocking a key part of a quest, or is this a nice to have? (helps us prioritize)

**Comment by jamesabowling** [comment]
Nice to have.

**Comment by toddmedema** [comment]
Closing this into the backlog for now, too many high importance bugs at the moment
