### ISSUE TITLE
Changing the "new quest" label to be quests with < 5 ratings

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#530]
@smartin015 What do you think? Would be a pretty easy ticket for Saumya, and I think is closer to our actual attention (bring attention to quests that are unknowns / unplayed, whilst highlighting that they are unknowns)

**Comment by smartin015** [comment]
SGTM. Should we remove the label if it's been played by the user though?

**Comment by toddmedema** [comment]
True. The logic for that might get tricky since it would mean quest searches on the API server would then have to reference user quests (slowing them down further). Might make sense to have that sort logic be in the client?

**Comment by Saumya29** [comment]
@toddmedema Can you elaborate, I didn't completely understand.

**Comment by toddmedema** [comment]
Ah, silly me, we changed the label from the text "new" to be the seedling icon. That'll make it easier to find in the code :)
