### ISSUE TITLE
 File manager / replace loading from Google Drive

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#535]
- [ ] Ability to see all your quests inside of the Quest Creator, ie an open file dialog that lists all of your quests sorted by most recent edit by default
  - [ ] maybe also a "recent quests" menu for 5 most recently edited quests
  - [ ] maybe also ability to sort quests by main columns (name, created, last edited)
  - [ ] maybe also ability to search quests by metadata (ie title, genre, language, etc)

**Comment by smartin015** [comment]
Additionally: show the most recent edited quest by default when going to the quest creator.

**Comment by toddmedema** [comment]
Looks like Drive has an API for this: https://developers.google.com/drive/api/v3/picker
