### ISSUE TITLE
Incorrect styling of search page checkboxes

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#554]
![image](https://user-images.githubusercontent.com/607666/48984230-5630d880-f0c7-11e8-9efd-e043b6091c9c.png)

The expansion checkboxes select in bright pink, which doesn't match the style of the rest of the app. I expect this is because we're using regular MUI checkboxes here and not components/base/Checkbox.tsx.

**Comment by toddmedema** [comment]
@nimish-gupta
