### ISSUE TITLE
Sentry error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#561]
Looks like hundreds of sessions + users have crashed in the past few weeks due to this bug :(

Init.tsx: https://sentry.io/fabricate-llc/expedition-app/issues/596335507/?query=is:unresolved
Multiplayer/middleware.tsx: https://sentry.io/fabricate-llc/expedition-app/issues/776501551/?query=is:unresolved
Multiplayer/middleware.tsx: https://sentry.io/fabricate-llc/expedition-app/issues/768955947/?query=is:unresolved
Android bundle: https://sentry.io/fabricate-llc/expedition-app/issues/582242098/?query=is:unresolved
Android bundle: https://sentry.io/fabricate-llc/expedition-app/issues/582242116/?query=is:unresolved

**Comment by smartin015** [comment]
The last time this happened was ~7 days ago on android and doesn't have the extra debugging info needed to determine what's going on. Closing this, let's reopen after the next app deploy if it recurs.
