### ISSUE TITLE
Switch "private quests" checkbox to use same checkbox setup as expansions

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#579]
Because we use abnormal checkboxes in search settings, the addition of an "Expedition" checkbox makes exposing private user quests unnecessarily important compared to the rest of the page.

![image](https://user-images.githubusercontent.com/607666/49551951-644cd900-f8bf-11e8-9a37-8b3f99e1c8c6.png)

**Comment by toddmedema** [comment]
@Saumya29 this would be a good one!
