### ISSUE TITLE
"Publish" button blocked by Contact Us

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#589]
Easiest solution would be to adjust dialog CSS so that there's more empty space beneath the dialog

<img width="284" alt="screen shot 2018-12-09 at 10 45 26" src="https://user-images.githubusercontent.com/775657/49699466-9734ec80-fb9f-11e8-9a0b-a7af623767c9.png">

**Comment by smartin015** [comment]
This only happens at 250% zoom - and even then, the publish button is still clickable. I think this is an edge case.

**Comment by toddmedema** [comment]
Re-opening since it's not zoom that's the problem, it's smaller screens (which are the majority screen size among non-software engineers) - you can simulate this by dragging your browser window to be smaller
