### ISSUE TITLE
Saving Settings in the quest creator

### ISSUE THREAD

**Issue by ChrisChinchilla** [ExpeditionRPG/expedition#612]
I can see a couple of issues and PRs that may relate to this, but slightly new to the project, so not entirely familiar with all the terminology. I wanted to test defining a number of creatures based on the player count, for example:

```
- Zombie
- Zombie
- {{ _.numAdventurers() > 3 }} Zombie
```

But to test this I need to change the player count, when I do so in the 'emulator' on the right, I change the player count, and when I click 'play from cursor', I see the count reset back to 1 again in a flash before my quest starts playing again.

Bug? Working as designed? In which case, how can I test the above? Or is what I'm trying to do a dumb idea anyway?

**Comment by toddmedema** [comment]
Ah! Yeah, this is a really good idea - essentially adding a settings panel to the quest creator letting you configure the settings that are used each time you play from cursor. Is that something you'd be interested in trying to add?

**Comment by ChrisChinchilla** [comment]
@toddmedema That's not exactly what I meant. What I meant was, when I go into the main settings panel for the emulator, settings don't save, and is that intentional, or a as designed?

**Comment by toddmedema** [comment]
I see. So, I'm seeing weird but workable behavior here. Made a very minimal quest:

```
# Title

_Card 1_

{{ _.numAdventurers() }}

_Card 2_

{{ _.numAdventurers() }}

**end**
```

If I hit play from cursor on card 1, change the settings to have a different player count, go back, then hit "next" to go to card 2, it correctly reflects the updated player count. So it is possible to play with adjusted settings, it just requires that you change them on the card before the one you want to test. This is the same as it works in the app itself, i.e. the settings change doesn't /really/ take effect until the next card.

**Comment by ChrisChinchilla** [comment]
@toddmedema OK, well as long as my functionality works, which I think does. Basically I want to add monsters depending on the player count, which seems pretty reasonable I think?

**Comment by toddmedema** [comment]
Yeah. Note that the expedition combat system does already try to balance damage based on number of players, so you shouldn't really need to do that unless you're manipulating the balance elsewhere as well (I.e. giving more loot if there is more players)

**Comment by toddmedema** [comment]
Backlogging since there's a workaround and this would be pretty complex to do well
