### ISSUE TITLE
Multiple monsters of the same type

### ISSUE THREAD

**Issue by ChrisChinchilla** [ExpeditionRPG/expedition#618]
I combed some of the quest creator guides and couldn't see anything, but is there a way or precedence to have a combat encounter with multiple monsters of the same type, or is it always encouraged to be random? I get that, but sometimes for theme, maybe you want to have a horde of the same creature.

**Comment by toddmedema** [comment]
Oh yeah, you can absolutely have multiple of the same monster! When you do that, the app will show users an additional instruction that they can use the backs of other enemy cards to serve as the duplicate monsters

**Comment by ChrisChinchilla** [comment]
@toddmedema Ahhh, I guess I should have just tried 😆
