### ISSUE TITLE
Bug with multiple lines of ops getting evaluated as a conditional paragraph

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#63]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Wednesday Jan 31, 2018 at 01:17 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-qdl/issues/59_

----

Ran into this edge case yet again:
```
{{ horrorExpansion = false }}
{{ demandGold = false }}
{{ hagClue = 0 }}
{{ townAnxiety = 3 }}
{{ dayHours = 0 }}
{{ gold = 0 }}
```

**Comment by JTimNolan** [comment]
Are we ok with a fix for this that changes our evaluation of all double-bracket MathJS expressions that are on their on their own single line into their own paragraph? My concern is essentially that some quest authors might be using this bug as a feature and breaking it may break their quest logic. e.g.
```
{{ horrorExpansion == false }}
{{ gold = 10 }}
```
Currently this sets gold to 10 if horrorExpansion is false, but the bugfix would cause it to always set gold = 10. This functionality isn't documented anywhere so I assume it would be undesirable. Actually in the current qdl docs there is an example where we do the opposite here: https://github.com/ExpeditionRPG/expedition/blob/master/services/quests/docs/qdl_guide.md#context

But I just want to check before potentially breaking somebody's quest!

**Comment by toddmedema** [comment]
Thanks for checking - that's ok in my mind, and as part of this update we can also update the docs to be more explicit about this functionality, ie that if you really want to do conditional setting it should be on the same line (`{{ horrorExpansion == false }} {{ gold = 10 }}`) (and also confirm that that works / add tests for that case :) )
