### ISSUE TITLE
Design returning backer badges & add to account page

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#631]
1x / 2x / 3x backer (might as well make 4x while we're at it)

Can pull a new field from the DB that Todd will then populate from Kickstarter records.

Probably worth thinking of badges as something a user could have multiple of / designing the DB to support that from the start. At the very least, having 1, 2, and 3x - but also potentially awarding badges for publishing your first quest, writing your first review, playing 10 quests, that sort of thing.

**Comment by smartin015** [comment]
Does the account page actually exist? I can't seem to find anything like it in the app.

**Comment by toddmedema** [comment]
Update: DB has been updated with user badges for all three kickstarters! Unfortunately, a lot of gaps / only about one third of KS backings got mapped to an account badge since lots of folks don't use gmail for their kickstarter, changed emails, etc
