### ISSUE TITLE
Splash page bug, auto advances on double tap without input

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#637]
If you double tap the splash page, sometimes it'll skip through the player / mode select screen without user input. Which, besides being annoying, can also break the app, since there's enough time to increase the player count, but it'll still be set to multitouch without you realizing it, which means the first time you hit combat, you'll have to restart the app b/c you won't be able to end combat.

**Comment by toddmedema** [comment]
In addition, would be good to attempt to auto-detect multitouch capability / default to no-multitouch when on such devices

**Comment by smartin015** [comment]
Looking around, there's multiple sets of rather-involved code that attempt to detect multitouch capability, but they're all flawed. I think it's fine if we just fix the bug with the splash screen and let players choose.
