### ISSUE TITLE
Quests missing ratings

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#642]
Some examples of quests that have been around for a long time, that seem to be missing their ratings / should have far more ratings:
- https://app.expeditiongame.com/#0B13T7uF-URoQV05ab1NJaHVoQ1U
- https://app.expeditiongame.com/#0B906tal7yj9BZ2xFM3REdUcyQ1k
- https://app.expeditiongame.com/#0B64Jpu_POkg_NE5NNF9fSW1UYWM

This is not good on multiple fronts, including so many new / unrated quests making the Expedition community look young to potential buyers, potential data loss, and players not being able to find the best quests.

**Comment by smartin015** [comment]
The feedback data is still there - I suspect we're somehow overwriting the cached rating columns in the Quests table when the quest is modified and republished. 

Related: [none of our publishing and rating update code is unit tested](https://github.com/ExpeditionRPG/expedition/blob/master/services/api/src/models/Quests.test.ts#L289)

**Comment by toddmedema** [comment]
Related: Just rated a quest with no ratings, and it didn't gain a rating: https://app.expeditiongame.com/#0B13T7uF-URoQV05ab1NJaHVoQ1U

Since ratings are part of the core experience / required to help users find good quests, and this problem is going to get worse with time (i.e. a larger and larger % of all quests will be marked as new with no ratings), I propose escalating this to high impact

**Comment by smartin015** [comment]
Updated the ratings in the prod DB (after taking a backup). The linked quests have a rating count equal to the number of feedback items received. There was a missing column in the Feedback DB which may have been preventing feedback from coming through... not sure the impact of that. It's now been fixed.

While testing it appears the code for ordering search results has also been broken for some time... will look to fix that now.
