### ISSUE TITLE
Add quest field: "Requires custom cards"

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#646]
Perhaps this should even be a text input, where the author pastes the card creator link to the cards required.

Needs a DB column, input in the quest creator, showing the icon + link in the app (in the quest details' "requires" section), and ideally a search filter to hide quests that require custom cards (i.e. "Show quests requiring custom cards", default true)

**Comment by smartin015** [comment]
Backlogging in favor of working on other high priority issues
