### ISSUE TITLE
Bug: Failed to load quest (invalid combat action)

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#656]
When playing through Kingdom of Kelendia: The Curse

`Failed to load quest (invalid combat action). Source: file:///android_asset/www/bundle.js line 102`

When trying to repro: "couldn’t click anything, including trying to save or report an error"

**Comment by toddmedema** [comment]
Also, the card Gabbie mentioned is `#FaeEight` - but I couldn't find anything wrong or suspicious about that card in particular:

```
_Fae Castle_(#FaeEight)

Room :rune_sowilo:

This room has a staircase leading upstairs.

Which door will you take?

* Stairway
 
  **goto FaeEleven**

* East Door
 
  **goto FaeSix**

* West Door
 
  **goto FaeTwo**
```

The best I can figure is that there's an undefined variable referenced somewhere, but I thought we had the crawler set up to detect those?

**Comment by toddmedema** [comment]
Closing as probably no longer relevant
