### ISSUE TITLE
Change all mentions of "Cards" to "Pages"

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#661]
Since cards are a different thing in the game + this is more story-appropriate vocab

**Comment by sciorms** [comment]
@toddmedema was this completed or closed due to other priorities?

**Comment by toddmedema** [comment]
Ah, so everything tagged with "backlog" was closed to keep the main list of issues cleaner - if it's tagged with backlog, it hasn't been completed yet (and once it's completed, the backlog tag can be removed)
