### ISSUE TITLE
Bug: Multiplayer allows 8 players, breaks search

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#682]
`WS: outbound #49: search({"params":{"language":"English","order":"+ratingavg","showPrivate":true,"text":"","expansions":[],"players":8},"players":8,"settings":{"audioEnabled":true,"autoRoll":false,"contentSets":{"horror":true,"future":true},"difficulty":"NORMAL","experimental":false,"fontSize":"NORMAL","multitouch":false,"numLocalPlayers":3,"showHelp":true,"simulator":false,"timerSeconds":10,"vibration":true}})`

**Comment by toddmedema** [comment]
Looks like this is fixed
