### ISSUE TITLE
Uncaught Error: nb

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#709]
```
Uncaught Error: nb file:///android_asset/www/bundle.js line 28
Uncaught Error: nb file:///android_asset/www/bundle.js line 28
```

"Message: Trying to log out... Error: Error: Uncaught Error: nb Source: file:///android_asset/www/bundle.js line 28"

**Comment by toddmedema** [comment]
Do we have any idea how to debug this? Seems like this is from a minified file, so we'd have to decompile it or something. I'd be ok closing this as won't fix given how many other bugs we have that we can reproduce & know how to fix

**Comment by toddmedema** [comment]
Closing this, as we've removed log out functionality
