### ISSUE TITLE
Streamline skill checks timed decision + mental math

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#714]
Recommendation from Greg: People are under a time crunch, but they are supposed to juggle discerning Persona type (dark or light) adding 1 to the roll if they match, then totaling all the skills of the chosen type (instead of just one).  I'd consider dropping instructions that make the roller check three different cards to tabulate a skill check #. 

Note that we'd still have to support two-aspect skill checks if any quests use it

**Comment by smartin015** [comment]
Backlogging to prioritize high impact bugs
