### ISSUE TITLE
Test API against Google cloud lowercasing (by Sept 30)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#722]
we recommend testing your project(s) using the method below prior to the start of the rollout on September 30, 2019. If your application receives requests from modern browsers, it is already exposed to lowercase header names, and no action is required on your part.

You can test your project by sending a request with the x-goog-downcase-all-headers request header, using any valid value, to trigger the new behavior in the load balancer. If your project experiences any issues, you can temporarily opt-out of the new behavior while you diagnose and resolve any issues with your client or server.

Example:
$ curl --http1.1 -H “x-goog-downcase-all-headers: x” http://example.com/

**Comment by SercanShortcut** [comment]
Hi @toddmedema,

Thanks for your post. I saw your comment below:
"If your application receives requests from modern browsers, it is already exposed to lowercase header names, and no action is required on your part."

Do you have any reference which confirms that? And is that valid for all web applications?

**Comment by toddmedema** [comment]
Hello! Google mentioned that in their email about this issue

**Comment by SercanShortcut** [comment]
Thanks. I found the email :)
https://pastebin.com/FQhWLxur

**Comment by smartin015** [comment]
Looks like this is due to a zombie GAE instance that isn't even used. Nothing do do here, #wontfix.
