### ISSUE TITLE
Viewing a quest should not reset played status

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#734]
"I'm using the web app. When I type in the beginning of the url in my browser address field, it autocompletes, usually, with the last URL I was on. For example "https://app.expeditiongame.com#0B7K9abSH1xEOeEZSVVMwNHNqaFE" but this take me into an existing quest. I couldn't figure out why Tutorial 2 kept showing up as uncompleted, but that appears to be why. When I go to that URL, it uncompletes the quest in my list. There appears to be no way to correct that once it happens except to click through the quest again. If there were a way to tick something to say the quest was completed, manually. Or, if the system kept persistent track of a quest having been completed the first time; but also tracked if it was in current progress, that would seem better to me."

Not totally sure why this happens since the User API should be getting the max timestamp of QUEST_END, so probably a bug -https://github.com/ExpeditionRPG/expedition/blob/master/services/api/src/models/Users.ts#L87

**Comment by smartin015** [comment]
Looks like we're just getting the most recent row matching a quest and user ID... the row could be any of "start", "end", or "stats".  `lastPlayed` currently doesn't indicate "last completed".

The fix would be to add `action` as a column to the query, group by `action`, and then extract the distinct timestamps of the last `start` and `end` events. This way we can show time of completion, as well as the last time the quest was most recently played regardless of if it was completed.

**Comment by smartin015** [comment]
Although at second glance, we do actually filter to "end" events. 

Also, I can't seem to repro the issue of the quest being un-completed when browsing to a quest ID. Maybe we've accidentally done something to fix this in the last several months.
