### ISSUE TITLE
Can't change a quest's Scarred Lands requirement unless also changing other expansions

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#739]
If you publish once with Scarred Lands required, publishing again with it disabled doesn't remove it. You have to do a dance where you also change at least one other expansion's state for Scarred Lands to get picked up...

Obviously a pretty bad user experience for quest creators if we're going to run a contest that involves this expansion in the next few months

**Comment by jamesabowling** [comment]
- If I uncheck The Horror and The Future then all expansion requirements disappear from the quest including Scarred Lands.
- If I re-check only The Horror, only The Horror expansion requirement will show
- If I re-check The Horror and The Future and re-publish (private or public) then the Scarred Lands requirement appears again along with The Horror and The Future

Checked this on newest iOS app and app.expedtiongame.com, Not sure if it's unique to my quest, but I'm afraid to test with my other quest in case that one catches the bug.

**Comment by toddmedema** [comment]
@jamesabowling fixed and deployed! Thank you for pointing this one out :)
