### ISSUE TITLE
Ability to see reviews on quest

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#765]
Ideally rating, date and text.

Probably by clicking on the rating on the quest details page, or maybe they load if you scroll down far enough.

Should be a separate API request per-quest / not part of the general search. Should only show reviews since the last major release.

Useful for both players (to get more insight into the quest beyond a single number), and authors (who can't currently see their reviews anywhere)

**Comment by smartin015** [comment]
Given the amount of open high-impact bugs and other smaller QoL improvement issues, I say we backlog this for now.
