### ISSUE TITLE
Chrome: Expedition Quest Editor Not Saving

### ISSUE THREAD

**Issue by HaraldHoerwick** [ExpeditionRPG/expedition#777]
The browser editor for Expedition continuously says "saving" but never saves. Checking the file in Google Drive shows that it has not saved, either.

**Comment by toddmedema** [comment]
Thanks for reporting this! That definitely sounds like a bug - and a real problem too. I've marked it as high impact and we'll get this sorted out asap

**Comment by smartin015** [comment]
I just tried to reproduce this problem on a new quest and failed. Could you paste a link to your quest here so we can try with yours?

**Comment by HaraldHoerwick** [comment]
I don't think it has to do with my code, it looks like after an hour or two
of working on it it just stops automatically saving. It could just be a
conflict between one of the extensions on my chrome browser. But if no one
else is experiencing it then its no big deal, I have just been copying and
pasting all of my work to a separate word doc just in case.

While I have you, can I ask a technical question about the
._numAdventurers() function? I have been trying to use it to display number
of players but every time I write it out {{ ._numAdventurers() }} nothing
is displayed, am I just missing something?

Sorry for the inconvenience and thank you for the quick response.

*Stepphan A. Stover*
tel: (864) 559-6285

**Comment by sciorms** [comment]
Not sure if this is still an issue. I used Chrome to test several quest concepts in the quest creator and they were all saved successfully to Google Drive even after being open for several hours. @toddmedema @smartin015
