### ISSUE TITLE
._numAdventurers error 427

### ISSUE THREAD

**Issue by HaraldHoerwick** [ExpeditionRPG/expedition#782]
While trying to use ._numAdventurers() to show/hide choices it throws and error 427: Failed to evaluate conditional on element. 

The bit of the code I was using it for goes:

* {{ ._numAdventurers() > 2 }} Players

I'm also unable to have it simply display the number of players with:

{{ _.numAdventurers() }}

**Comment by toddmedema** [comment]
Looks like you might have the . and _ backwards, the _ comes first `_.numAdventurers()`

**Comment by HaraldHoerwick** [comment]
I just noticed I wrote that, I have been working on this for too long. Thank you.
