### ISSUE TITLE
[In progress] Node 8.10 EoL (AWS Lambda) by Feb 3 -> update to Node 12

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#804]
The Node community has decided to end support for Node.js 8.x on December 31, 2019 [1]. From this date forward, Node.js 8.x will stop receiving bug fixes, security updates, and/or performance improvements. To ensure that your new and existing functions run on a supported and secure runtime, language runtimes that have reached their EOL are deprecated in AWS [2].

For Node.js 8.x, there will be 2 stages to the runtime deprecation process:

1. Disable Function Create – Beginning January 6, 2020, customers will no longer be able to create functions using Node.js 8.10

2. Disable Function Update – Beginning February 3, 2020, customers will no longer be able to update functions using Node.js 8.10

**Comment by toddmedema** [comment]
Do we use Lambda at all, or do we just need to update it for the API server?

**Comment by toddmedema** [comment]
@smartin015 I assume this is no longer relevant?
