### ISSUE TITLE
Screen sizing bug

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#806]
![Screenshot_20191026-170419_Expedition](https://user-images.githubusercontent.com/775657/67625929-bb7ad580-f812-11e9-8bc0-2801ccd8c774.jpg)

**Comment by toddmedema** [comment]
Looks like this is still an issue:
"On the rating screen, at the end of a scenario, sometimes the rating screen is zoomed in, but you can't move the screen left or right to show more than 3 stars as the highest rating you can give a scenario, although scrolling up and down appears to work without issue. My fiance and I have both experienced this in the past on our Samsung devices (Moto E4+ and Moto g5s). The latest time it happened was on the Starstriders scenario. Settings on our devices were sounds off, normal difficulty, 15 second timer, 2 player, and only Tech and Horror expansions."

![Screenshot_20200206-193436](https://user-images.githubusercontent.com/775657/74105730-61d2b880-4b2e-11ea-82bd-ea292ae5ee0b.png)

**Comment by toddmedema** [comment]
It no longer seems to be just the rating screen, here's a screenshot of it happening on a quest page on a Moto 7
![Screenshot_20200213-172302](https://user-images.githubusercontent.com/775657/74581742-e1261900-4f80-11ea-9140-27340807d437.png)

**Comment by Drakensin** [comment]
my notes for the Moto 7 (Moto G7 Power) it happens Everytime I use the latest beta Android app @toddmedema

**Comment by Drakensin** [comment]
every story I done that has more than a specific amount of words has this issue
