### ISSUE TITLE
Tutorial (LTP1 quest) should better explain combat card drawing / shuffling

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#810]
User feedback: "The game should explain which cards are reshuffled during combat more clearly. Are used actions reshuffled every round? Are drawn but unused actions reshuffled?"

**Comment by sciorms** [comment]
Submitted PR to address this issue: https://github.com/ExpeditionRPG/expedition/pull/838

**Comment by sciorms** [comment]
@toddmedema can this issue be closed per PR #838 ?

**Comment by toddmedema** [comment]
Yep! If you put "fixes #xxx" in your pr description, it'll auto close them :)
