### ISSUE TITLE
Bug: Can select 7 ppl with multitouch

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#811]
And then no quests show up in search

Obv don't want to cap it behind the scenes without telling them, since that'd be confusing ... perhaps we show a modal on the next screen saying "you tried 7+ people, but we capped it to 6 since Expedition only supports 1-6 players"

**Comment by Lordtien** [comment]
Is showing a dialog on the splash screen possible? It seems more intuitive to stop the transition there so that users can choose an appropriate number of people. Let me know what you think.

**Comment by toddmedema** [comment]
We should ideally stop the transition, and show a dialog, so that they see the message "too many people", but are still on the splash screen so that they can redo it

We can show a dialog on any screen, because it's implemented at the compositor level https://github.com/ExpeditionRPG/expedition/blob/master/services/app/src/components/Compositor.tsx#L186
