### ISSUE TITLE
Verify no passwords, only OAuth2

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition#816]
From an email...

> Starting February 15, 2021, G Suite accounts will only allow access to apps using OAuth. Password-based access will no longer be supported.

> To maintain compatibility with G Suite accounts, update your app to use OAuth 2.0 as a connection method. To get started, follow our developer guide on using OAuth 2.0 to access Google APIs. You can also refer to our guide on OAuth 2.0 for mobile & desktop apps.

**Comment by toddmedema** [comment]
@smartin015 Are we using anything that's part of the "G Suite" for Expedition, or is this just for gmail?

.... oh, probably email sending on the API server...
